default: help

help:
	@just --list

setup:
	uv venv
	uv pip install -e ".[dev]"

test:
	uv run pytest

coverage:
	uv run pytest --cov=src

lint:
	uv run ruff check src tests
	uv run mypy src tests

format:
	uv run ruff check --fix src tests
	uv run ruff format src tests

run +args="--help":
	uv run {{ cookiecutter.project_slug }} {{ "{{args}}" }}
